server: 
  port: 80
com: 
  baixiangfood: 
    eid: 9406957
    signDataKey: nTd0rxqUGD0PlF9XUli5QpyJfGEkNYa9
spring:
    datasource:
        name: test01
        url: jdbc:mysql://47.104.128.16:3306/SignInObtain
        username: root
        password: junhahahaha156
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mappings/*.xml
  type-aliases-package: com.baixiangfood.model
#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql